-- health4ai schema — GENERATED by scripts/build_schema_sql.sh from supabase/bootstrap/001 + 002.
-- Do not edit this file. Edit the bootstrap files and re-run the script.
--
-- SUPABASE ONLY. Run it in the SQL editor of a Supabase project YOU own, then deploy the ingest
-- function (supabase functions deploy healthkit-ingest). It references auth.users; plain
-- Postgres such as Neon or a local Docker container is not a supported backend for the app.
--
-- History: this path used to serve a separate "portable" schema with row-level security
-- commented out. Applied as the postgres role on the stock Supabase image, that let the anon
-- role SELECT and INSERT every health row. It also lacked the ingest function, so the app could
-- not sync to it at all. Replaced 2026-09-12. Register D353.

-- health4ai — schema for a backend YOU control
--
-- health4ai never operates a backend for your health data. This file is the
-- schema you install in your own Supabase project so the iOS app has somewhere to
-- sync to. Run 001 then 002, then deploy the healthkit-ingest Edge Function.
--
-- SUPABASE ONLY. It references auth.users, and the app authenticates through Supabase Auth
-- and writes through a Supabase Edge Function. Plain Postgres (Neon, local Docker) has
-- neither, and health4ai ships no other ingest path. An earlier line here said "or any
-- Postgres"; that was never true of the app.
--
-- It supersedes the older numbered migrations and fixes two defects in them:
--
--   1. The sample unique key now includes source_device. Without it, a night
--      recorded by BOTH an Apple Watch and an Oura Ring collapses to a single
--      row and one device's data is silently lost. Fine for one device, wrong
--      the moment you wear two.
--
--   2. Daily rollups use YOUR time zone instead of a hardcoded America/New_York,
--      so day boundaries land where you actually live.
--
-- Run it against a project you own and nothing else. It creates tables in the
-- public schema and assumes they are yours to create.

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Raw samples
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.healthkit_metrics (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  metric_type   text        NOT NULL,
  value         float8,
  unit          text,
  source_device text        NOT NULL DEFAULT '',
  started_at    timestamptz NOT NULL,
  ended_at      timestamptz,
  metadata      jsonb,
  synced_at     timestamptz NOT NULL DEFAULT now(),
  -- source_device IS part of the key, unlike the legacy project.
  -- healthkit-ingest carries a comment admitting the narrow key collapses
  -- same-timestamp multi-device samples to one row and calling that
  -- "acceptable for single-user personal use". This build is not single-user:
  -- a tester wearing both an Apple Watch and an Oura Ring would silently lose
  -- one device's night. NOT NULL DEFAULT '' keeps the key total — in Postgres
  -- a NULL member makes a UNIQUE constraint stop deduping.
  CONSTRAINT healthkit_metrics_user_metric_device_started_key
    UNIQUE (user_id, metric_type, source_device, started_at)
);

CREATE INDEX IF NOT EXISTS healthkit_metrics_user_time_idx
  ON public.healthkit_metrics (user_id, started_at DESC);
CREATE INDEX IF NOT EXISTS healthkit_metrics_user_type_time_idx
  ON public.healthkit_metrics (user_id, metric_type, started_at DESC);
CREATE INDEX IF NOT EXISTS healthkit_metrics_metadata_idx
  ON public.healthkit_metrics USING gin(metadata);

-- ---------------------------------------------------------------------------
-- 2. Daily rollups
-- ---------------------------------------------------------------------------
-- Column is `summary_date`. The legacy project has TWO contradictory
-- definitions of this table: 009 declares `summary_date`, while the
-- summarize function in 003 writes `date`. Live is `date`, which proves 009's
-- CREATE ... IF NOT EXISTS silently no-opped against the pre-existing table and
-- the migration file has not described that project since. One name here, and
-- the function below is written against it.
CREATE TABLE IF NOT EXISTS public.healthkit_daily_summaries (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  metric_type   text        NOT NULL,
  summary_date  date        NOT NULL,
  avg_value     float8,
  min_value     float8,
  max_value     float8,
  sum_value     float8,
  sample_count  integer,
  -- NOT NULL because `unit` is part of the unique key below, and NULL <> NULL would
  -- let two NULL-unit rows for one day both insert and never upsert.
  unit          text        NOT NULL DEFAULT '',
  created_at    timestamptz NOT NULL DEFAULT now(),
  summarized_at timestamptz NOT NULL DEFAULT now(),
  -- `unit` is in the key: a daily summary is per (user, metric_type, date, UNIT).
  -- Without it the summariser summed a metric across units and stamped the total with
  -- MAX(unit) — 0.032 kg + 32 g of protein became 32.032 kg. Register D338.
  CONSTRAINT healthkit_daily_summaries_user_metric_date_key
    UNIQUE (user_id, metric_type, summary_date, unit)
);

CREATE INDEX IF NOT EXISTS healthkit_daily_summaries_user_date_idx
  ON public.healthkit_daily_summaries (user_id, summary_date DESC);

-- ---------------------------------------------------------------------------
-- 3. Per-user settings
-- ---------------------------------------------------------------------------
-- The legacy sleep/quantity views hardcode 'America/New_York' and an Oura-only
-- source filter. Both are Jeff's setup, not a product. A hosted build needs the
-- timezone per user or every rollup is wrong for anyone outside Eastern.
CREATE TABLE IF NOT EXISTS public.health4ai_user_settings (
  user_id    uuid        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  time_zone  text        NOT NULL DEFAULT 'UTC',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT health4ai_user_settings_tz_valid
    CHECK (now() AT TIME ZONE time_zone IS NOT NULL)
);

-- ---------------------------------------------------------------------------
-- 4. Waitlist (with TestFlight invite state)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.health4ai_waitlist (
  id             uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  email          text        NOT NULL UNIQUE,
  created_at     timestamptz NOT NULL DEFAULT now(),
  -- Explicit, recorded consent to be handed to Apple as a TestFlight tester.
  -- App Store Connect administrators can see tester email addresses, so this is
  -- a disclosure to a third party and needs a yes on the record, not an
  -- inference from "they joined a waitlist".
  consent_testflight boolean     NOT NULL DEFAULT false,
  consent_source     text,
  invite_status      text        NOT NULL DEFAULT 'pending',
  invited_at         timestamptz,
  asc_tester_id      text,
  last_error         text,
  CONSTRAINT health4ai_waitlist_email_format
    CHECK (char_length(email) <= 254 AND email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  CONSTRAINT health4ai_waitlist_invite_status_valid
    CHECK (invite_status IN ('pending','queued','invited','failed','declined','skipped')),
  -- An invited row must carry its evidence. Without this an invite run can
  -- report success while writing nothing that proves Apple accepted the tester.
  CONSTRAINT health4ai_waitlist_invited_has_evidence
    CHECK (invite_status <> 'invited' OR (invited_at IS NOT NULL AND asc_tester_id IS NOT NULL)),
  -- Consent gates the invite at the DB, not only in the invite script. A bug
  -- in that script must not be able to hand a non-consenting address to Apple.
  CONSTRAINT health4ai_waitlist_invite_requires_consent
    CHECK (invite_status NOT IN ('queued','invited') OR consent_testflight)
);

CREATE INDEX IF NOT EXISTS health4ai_waitlist_invite_status_idx
  ON public.health4ai_waitlist (invite_status, created_at);

CREATE OR REPLACE FUNCTION public.health4ai_waitlist_normalize_email()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.email := lower(btrim(NEW.email));
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_health4ai_waitlist_normalize ON public.health4ai_waitlist;
CREATE TRIGGER trg_health4ai_waitlist_normalize
  BEFORE INSERT OR UPDATE ON public.health4ai_waitlist
  FOR EACH ROW EXECUTE FUNCTION public.health4ai_waitlist_normalize_email();

COMMIT;


-- health4ai — grants, RLS, and the summarize function. Run after 001.
--
-- Posture: default-deny. Every grant below is column- or row-scoped and exists
-- because a specific screen in the app needs it. The failure mode this avoids is
-- the common one: broad table grants to `authenticated` with RLS as the only
-- thing standing behind them. Nothing here is granted "to be safe".

BEGIN;

-- ---------------------------------------------------------------------------
-- 0. Start from zero
-- ---------------------------------------------------------------------------
REVOKE ALL ON public.healthkit_metrics         FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.healthkit_daily_summaries FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.health4ai_user_settings   FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.health4ai_waitlist        FROM PUBLIC, anon, authenticated;

ALTER TABLE public.healthkit_metrics         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.healthkit_daily_summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.health4ai_user_settings   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.health4ai_waitlist        ENABLE ROW LEVEL SECURITY;

-- Future tables in this schema start denied rather than inheriting Supabase's
-- default grants. Without this, a migration can REVOKE a grant while live state
-- quietly disagrees, and the file stops describing the database.
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM anon, authenticated;

-- ---------------------------------------------------------------------------
-- 1. Health data — read and delete your own; writes go through the ingest fn
-- ---------------------------------------------------------------------------
-- READ is granted, unlike legacy 009 which denied all client access. A hosted
-- consumer app has to render the user's own numbers on-device; without this the
-- Today screen has no data source and the product is a write-only pipe.
--
-- DELETE is granted deliberately: a health app must let a person destroy their
-- own data on demand, and routing that through support tickets is not a
-- privacy control. INSERT/UPDATE stay denied — the client never decides what
-- user_id a row carries. healthkit-ingest validates the JWT and stamps user_id
-- from it, then writes with the service role, which bypasses RLS.
GRANT SELECT, DELETE ON public.healthkit_metrics         TO authenticated;
GRANT SELECT, DELETE ON public.healthkit_daily_summaries TO authenticated;

CREATE POLICY metrics_own_rows ON public.healthkit_metrics
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY metrics_delete_own ON public.healthkit_metrics
  FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE POLICY summaries_own_rows ON public.healthkit_daily_summaries
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY summaries_delete_own ON public.healthkit_daily_summaries
  FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 2. Settings — full own-row control
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE ON public.health4ai_user_settings TO authenticated;

CREATE POLICY settings_select_own ON public.health4ai_user_settings
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY settings_insert_own ON public.health4ai_user_settings
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY settings_update_own ON public.health4ai_user_settings
  FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 3. Waitlist — anon may submit an address and a consent flag, nothing else
-- ---------------------------------------------------------------------------
-- Column-level INSERT is the control that matters. With a table-level grant,
-- anyone holding the publishable key (it ships in the landing page by design)
-- could POST invite_status='invited' with a forged asc_tester_id and corrupt
-- the invite ledger. They cannot name a column they were not granted.
--
-- No SELECT for anon. The legacy table got this right and it is repeated here:
-- an email list that can be read back with a public key is a harvestable list.
GRANT INSERT (email, consent_testflight, consent_source)
  ON public.health4ai_waitlist TO anon;

CREATE POLICY waitlist_anon_insert ON public.health4ai_waitlist
  FOR INSERT TO anon WITH CHECK (true);

GRANT ALL ON public.health4ai_waitlist TO service_role;

-- ---------------------------------------------------------------------------
-- 4. Summarize function
-- ---------------------------------------------------------------------------
-- Ported from legacy 003 with two fixes: it writes `summary_date` (the legacy
-- copy wrote `date` and disagreed with the legacy table definition), and the
-- rollup day boundary comes from the user's own time zone instead of a
-- hardcoded America/New_York.
CREATE OR REPLACE FUNCTION public.summarize_healthkit_metric(
  p_user_id     uuid,
  p_metric_type text,
  p_cutoff      date
)
RETURNS TABLE(raw_count bigint, summary_days bigint)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $func$
DECLARE
  v_raw_count    bigint;
  v_summary_days bigint;
  v_tz           text;
BEGIN
  SELECT coalesce(s.time_zone, 'UTC') INTO v_tz
  FROM public.health4ai_user_settings s WHERE s.user_id = p_user_id;
  v_tz := coalesce(v_tz, 'UTC');

  SELECT count(*) INTO v_raw_count
  FROM public.healthkit_metrics
  WHERE user_id = p_user_id AND metric_type = p_metric_type
    AND started_at < p_cutoff::timestamptz;

  IF v_raw_count = 0 THEN
    RETURN QUERY SELECT 0::bigint, 0::bigint;
    RETURN;
  END IF;

  INSERT INTO public.healthkit_daily_summaries
    (user_id, metric_type, summary_date, avg_value, min_value, max_value,
     sum_value, sample_count, unit)
  -- GROUP BY carries `unit`, and the unit is no longer invented with max(). Without
  -- this a day holding one metric in two units summed across both and was labelled
  -- with whichever string sorted higher. Register D338.
  SELECT user_id, metric_type, (started_at AT TIME ZONE v_tz)::date,
         avg(value), min(value), max(value), sum(value), count(*), COALESCE(unit, '')
  FROM public.healthkit_metrics
  WHERE user_id = p_user_id AND metric_type = p_metric_type
    AND started_at < p_cutoff::timestamptz
  GROUP BY user_id, metric_type, (started_at AT TIME ZONE v_tz)::date, COALESCE(unit, '')
  ON CONFLICT (user_id, metric_type, summary_date, unit) DO UPDATE SET
    avg_value = EXCLUDED.avg_value, min_value = EXCLUDED.min_value,
    max_value = EXCLUDED.max_value, sum_value = EXCLUDED.sum_value,
    sample_count = EXCLUDED.sample_count,
    summarized_at = now();
    -- `unit` is not reassigned: it is part of the conflict key, so EXCLUDED.unit is
    -- always the existing value.

  GET DIAGNOSTICS v_summary_days = ROW_COUNT;

  DELETE FROM public.healthkit_metrics
  WHERE user_id = p_user_id AND metric_type = p_metric_type
    AND started_at < p_cutoff::timestamptz;

  RETURN QUERY SELECT v_raw_count, v_summary_days;
END;
$func$;

-- SECURITY DEFINER + a user_id PARAMETER is a lethal pairing if it is callable
-- from a client: any signed-in user could summarize (and therefore DELETE) any
-- other user's raw rows. PostgreSQL grants EXECUTE to PUBLIC by default, so the
-- revoke is required, not tidy-up. Legacy 009 learned this the same way.
REVOKE ALL ON FUNCTION public.summarize_healthkit_metric(uuid, text, date)
  FROM PUBLIC, anon, authenticated;

-- The waitlist trigger function is created in 001, BEFORE the ALTER DEFAULT PRIVILEGES above,
-- and default privileges are prospective only, so it kept PostgreSQL's default EXECUTE to PUBLIC.
-- Not exploitable (it reads NEW, which exists only in trigger context), but this file says
-- default-deny, so make that true of every function it ships. Revoking EXECUTE does not stop the
-- trigger firing: the privilege is checked when the trigger is created, not each time it fires.
REVOKE ALL ON FUNCTION public.health4ai_waitlist_normalize_email() FROM PUBLIC, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 5. Merged hourly totals replace per-device rows
-- ---------------------------------------------------------------------------
-- For activity types that several devices record at the same moment (steps, distance,
-- energy, flights, exercise/move/stand time) the app sends HealthKit's merged total per UTC
-- hour, labelled source_device 'HealthKit (all sources)'. Rows already stored per device for
-- that hour would be summed on top of it: an iPhone and a Watch counting the same steps is
-- how 2021 came to read 67% high. So the hour's per-device rows are deleted and the merged
-- row written in ONE transaction; done as two requests, a failure between them left the hour
-- either double-counted or empty. A per-device row belongs to the hour its started_at falls
-- in, so a sample crossing a boundary is replaced when the hour it started in arrives.
-- Register D361.
CREATE OR REPLACE FUNCTION public.health4ai_replace_merged_hours(
  p_user_id uuid,
  p_rows    jsonb
)
RETURNS TABLE(deleted_count bigint, written_count bigint)
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $func$
DECLARE
  v_deleted bigint;
  v_written bigint;
BEGIN
  IF p_user_id IS NULL THEN
    RAISE EXCEPTION 'p_user_id is required';
  END IF;
  IF p_rows IS NULL OR jsonb_typeof(p_rows) <> 'array' THEN
    RAISE EXCEPTION 'p_rows must be a JSON array';
  END IF;

  DELETE FROM public.healthkit_metrics m
  USING jsonb_to_recordset(p_rows) AS r(metric_type text, started_at timestamptz)
  WHERE m.user_id = p_user_id
    AND m.metric_type = r.metric_type
    AND m.started_at >= r.started_at
    AND m.started_at <  r.started_at + interval '1 hour'
    AND m.source_device <> 'HealthKit (all sources)';
  GET DIAGNOSTICS v_deleted = ROW_COUNT;

  INSERT INTO public.healthkit_metrics
    (user_id, metric_type, value, unit, source_device, started_at, ended_at, metadata)
  SELECT p_user_id, r.metric_type, r.value, r.unit, 'HealthKit (all sources)',
         r.started_at, r.ended_at, r.metadata
  FROM jsonb_to_recordset(p_rows) AS r(metric_type text, value double precision, unit text,
                                       started_at timestamptz, ended_at timestamptz, metadata jsonb)
  ON CONFLICT (user_id, metric_type, source_device, started_at) DO UPDATE SET
    value = EXCLUDED.value, unit = EXCLUDED.unit,
    ended_at = EXCLUDED.ended_at, metadata = EXCLUDED.metadata;
    -- The same columns the ingest function's PostgREST upsert sets; synced_at keeps its
    -- insert-time default there too.
  GET DIAGNOSTICS v_written = ROW_COUNT;

  RETURN QUERY SELECT v_deleted, v_written;
END;
$func$;

-- A user_id PARAMETER on a function a client could call would let any signed-in user delete
-- any other user's rows, and PostgreSQL grants EXECUTE to PUBLIC by default. Only the ingest
-- function calls this, with the service role, after verifying the caller's JWT itself.
REVOKE ALL ON FUNCTION public.health4ai_replace_merged_hours(uuid, jsonb)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.health4ai_replace_merged_hours(uuid, jsonb) TO service_role;

COMMIT;
