#!/bin/bash
# Regenerates web/public/schema.sql (served at https://health4.ai/schema.sql) from
# supabase/bootstrap/001 + 002, so the file every README, blog post and page links to is the
# SAME default-deny schema the app is tested against — never a second, drifting copy.
set -euo pipefail
cd "$(dirname "$0")/.."
{
cat <<'HDR'
-- health4ai schema — GENERATED by scripts/build_schema_sql.sh from supabase/bootstrap/001 + 002.
-- Do not edit this file. Edit the bootstrap files and re-run the script.
--
-- SUPABASE ONLY. Run it in the SQL editor of a Supabase project YOU own, then deploy the ingest
-- function (supabase functions deploy healthkit-ingest). It references auth.users; plain
-- Postgres such as Neon or a local Docker container is not a supported backend for the app.
--
-- History: this path used to serve a separate "portable" schema with row-level security
-- commented out. Applied as the postgres role on the stock Supabase image, that let the anon
-- role SELECT and INSERT every health row. It also lacked the ingest function, so the app could
-- not sync to it at all. Replaced 2026-09-12. Register D353.

HDR
cat supabase/bootstrap/001_health4ai_prod_bootstrap.sql
printf '\n\n'
cat supabase/bootstrap/002_health4ai_prod_rls.sql
} > web/public/schema.sql
echo "wrote web/public/schema.sql ($(wc -c < web/public/schema.sql | tr -d ' ') bytes)"
